name: Windows CI

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache vanilla assets
      uses: actions/cache@v2
      env:
        cache-name: cache-vanilla-assets
      with:
        path: src/deps/elona
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('src/deps/elona/elona/version_en.txt') }}
    - name: Run REPL test
      run: |
        ./OpenNefia verify -l
        ./OpenNefia test
